In [2]:
from numpy.random import hypergeometric,uniform
from numpy import (array, where, sum, sin, cos, arange, linspace, exp, sqrt, pi, zeros, max, min, round, argsort, flip)


In [17]:
def text_scatter(x, y, char_lim_x = 37, char_lim_y = 21, symb = ".", pad = .1):
    if len(x) != len(y):
        raise Exception("x and y must be the same length")
    if len(x) == 0 or len(y) == 0:
        raise Exception("Data must have a length greater than 0")
    x = array(x)
    y = array(y)
    
    points = zeros((char_lim_y - 1, char_lim_x - 1)).astype(bool)
    fx = char_lim_x - 2
    fy = char_lim_y - 2
    maX = max(x)
    maY = max(y)
    miX = min(x)
    miY = min(y)
    
    new_x = round(fx * (x - miX) / (maX - miX)).astype(int)
    new_y = round(fy * (y - miY) / (maY - miY)).astype(int)

    indices = (new_y, new_x)

    points[indices] = True

    chars = zeros(points.shape).astype(str)

    chars[where(points != True)] = " "
    chars[where(points)] = symb
    chars = flip(chars, axis=0)
    
    for row in chars:
        print("".join(row))



x = array([2, 4, 5, 3, 8, 9])
y = uniform(5, 70, len(x))
print(f'y values: {y}\nx values: {x}')
text_scatter(x,y, char_lim_x=10, char_lim_y=10)

y values: [55.2053642  12.23216461 57.08168927 10.27882116  8.42637224 42.88067719]
x values: [2 4 5 3 8 9]
.  .     
         
        .
         
         
         
         
  .      
 .     . 


In [35]:
x = arange(-2, 2 + .1, 1/5)
y = x**2
text_scatter(x,y, symb="/")

/                                  /
                                    
                                    
                                    
  /                              /  
                                    
                                    
    /                           /   
                                    
                                    
     /                        /     
                                    
       /                    /       
                                    
         /                /         
                                    
          /             /           
            /          /            
              /      /              
                / //                


In [21]:
temp = arange(9).reshape(3,-1)
temp, flip(temp, axis=0), flip(temp, axis=1)

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[6, 7, 8],
        [3, 4, 5],
        [0, 1, 2]]),
 array([[2, 1, 0],
        [5, 4, 3],
        [8, 7, 6]]))